(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" default))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#042028" :foreground "#819090" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Menlo"))))
 '(company-preview ((t (:foreground "wheat"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "#465b62"))))
 '(company-scrollbar-bg ((t (:inherit company-tooltip :background "#092832"))))
 '(company-scrollbar-fg ((t (:background "#eae3cc"))))
 '(company-tooltip ((t (:background "#13394c" :foreground "#839496"))))
 '(company-tooltip-common ((t (:inherit company-tooltip :foreground "#821117"))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :foreground "#d11a24"))))
 '(company-tooltip-selection ((t (:inherit company-tooltip :background "#022028"))))
 '(custom-link ((t (:foreground "#2076c8"))))
 '(custom-mode-default ((t (:inherit autoface-default :foreground "#ffffff" :height 130 :family "Inconsolata"))) t)
 '(custom-variable-tag ((t (:foreground "#2076c8" :weight bold))))
 '(echo-area ((t (:stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 120 :width normal :family "Menlo"))) t)
 '(font-lock-builtin-face ((t (:foreground "#6193B3" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#53686f" :inverse-video nil :underline nil :slant italic :weight normal))))
 '(font-lock-constant-face ((t (:foreground "DeepSkyBlue3"))))
 '(font-lock-function-name-face ((t (:foreground "#195fa1"))))
 '(font-lock-variable-name-face ((t (:foreground "#2076c8"))))
 '(git-commit-mode-default ((t (:inherit text-mode-default :height 120 :family "Menlo"))) t)
 '(helm-buffer-file ((t (:inherit font-lock-constant-face))))
 '(helm-ff-directory ((t (:foreground "#2076c8"))))
 '(helm-ff-dotted-directory ((t (:foreground "#2778C5"))))
 '(helm-ff-executable ((t (:foreground "#a67721"))))
 '(helm-ff-file ((t (:inherit default))))
 '(helm-ff-symlink ((t (:foreground "#259185"))))
 '(helm-match ((t (:foreground "#a67721"))))
 '(helm-selection ((t (:background "#0f3f4e" :underline t))))
 '(helm-selection-line ((t (:background "#0f3f4e"))))
 '(helm-source-header ((t (:background "#22083397778B" :foreground "white" :weight extra-bold :height 1.3 :family "Sans Serif"))))
 '(helm-visible-mark ((t (:background "#4d5b17"))))
 '(help-mode-default ((t (:inherit special-mode-default))) t)
 '(highlight ((t (:background "#1c4c5e"))))
 '(hl-line ((t (:background "#072A34"))))
 '(minibuffer-inactive-mode-default ((t (:inherit autoface-default))) t)
 '(minibuffer-prompt ((t (:foreground "#2076c8" :inverse-video nil :underline nil :slant normal :weight bold))))
 '(mode-line ((t (:background "#012B35" :foreground "gray60" :inverse-video nil :box nil :underline nil :slant normal :weight normal))))
 '(mode-line-emphasis ((t nil)))
 '(mode-line-highlight ((t nil)))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#8b134f"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#384311"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#384311"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#384311"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#384311"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#384311"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#384311"))))
 '(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-depth-1-face :foreground "#384311"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#d11a24"))))
 '(region ((t (:background "#0f3f4e"))))
 '(show-paren-match ((t (:background "#0a2832" :foreground "#c71b6f" :inverse-video nil :underline nil :slant normal :weight bold))))
 '(sp-show-pair-match-face ((t (:foreground "#c71b6f"))))
 '(sp-show-pair-mismatch-face ((t (:background "#810160"))))
 '(variable-pitch ((t (:slant normal :weight normal :height 130 :width normal :foundry "nil" :family "Menlo")))))
